### ISSUE TITLE
Enable ESLint and Prettier (grpc folder)

### ISSUE THREAD

**Issue by carloshellin** [propagamap/openelevationservice#26]
**Low priority**
Enable the use of ESLint and Prettier in this repository (grpc folder). Take the frontend repo as a reference: https://github.com/propagamap/frontend/blob/main/.eslintrc.cjs and https://github.com/propagamap/frontend/blob/main/.prettierrc.json (keep in mind that you'll probably have to modify it to remove things related to next, which is only for the frontend). More info at https://typescript-eslint.io/
Once it's enabled, let me know so that I can activate the eslint workflow (https://github.com/propagamap/workflows/blob/refs/heads/main/eslint.yml) in this repository.

**Comment by liu-hanli** [comment]
ESLint is not needed for Node in this project, the code are program generated.
Prettier added.
