### ISSUE TITLE
Check Dependabot Alerts

### ISSUE THREAD

**Issue by carloshellin** [propagamap/openelevationservice#28]
**Medium priority**
By enabling dependabot, several PRs have been created that you need to manage.

- Check that you have access to: https://github.com/propagamap/openelevationservice/security/dependabot and https://github.com/propagamap/openelevationservice/security/secret-scanning
- Review the security advisories. Make sure there is already a PR or create one to resolve possible dependency conflicts (if possible).
- Ensure that the implementation of your code maintains its functionality.
- Any new security alerts should be handled in subsequent iterations.

**Comment by liu-hanli** [comment]
Done
